# Generated by Django 6.1.1 on 2026-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='fecha_utilizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='utilizado',
            field=models.BooleanField(default=False),
        ),
    ]
