# Generated by Django 6.1.1 on 2026-09-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('numero_bus', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('SEMICAMA', 'Semicama'), ('CAMA', 'Cama')], max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='transporte.bus')),
            ],
            options={
                'ordering': ['bus', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='transporte.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='transporte.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='AsientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado')], default='DISPONIBLE', max_length=10)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asignados', to='transporte.asiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_servicio', to='transporte.servicio')),
            ],
            options={
                'ordering': ['asiento__numero'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminales', to='transporte.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='terminal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='transporte.terminal'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='terminal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='transporte.terminal'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('bus', 'numero'), name='unique_asiento_bus'),
        ),
        migrations.AddConstraint(
            model_name='asientoservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'asiento'), name='unique_asiento_servicio'),
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('nombre', 'ciudad'), name='unique_terminal_ciudad'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('terminal_origen', 'terminal_destino'), name='unique_ruta_origen_destino'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('terminal_origen', models.F('terminal_destino')), _negated=True), name='ruta_origen_destino_diferentes'),
        ),
    ]
