# Generated by Django 6.1.1 on 2026-09-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroPasajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro_pasajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ocupante', models.CharField(max_length=150)),
                ('documento_ocupante', models.CharField(max_length=30)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('asiento_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carro', to='transporte.asientoservicio')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservas.carropasajes')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carro', 'asiento_servicio'), name='unique_asiento_en_carro')],
            },
        ),
    ]
