# Generated by Django 6.1.1 on 2026-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carropasajes',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LIQUIDADO', 'Liquidado')], default='ACTIVO', max_length=10),
        ),
    ]
